### ISSUE TITLE
Stickynotes: Consider Masonry.js

### ISSUE THREAD

**Issue by blunket** [emily04/emily04.github.io#2]
Consider this library for improving the sticky notes design!
https://masonry.desandro.com/

ALSO: Consider Masonry.js as an option maybe for displaying your projects, too!

Also consider some class overrides! for example:
```css
.card.yellow > h1{
  background-color: #ff6;
}
.card.blue > h1{
  background-color: #66f;
}

.yellow .caption{
  background-color: #ff9;
}
.blue .caption{
  background-color: #99f;
}
```

Preview:
![image](https://user-images.githubusercontent.com/17580512/43667600-532e70c6-973e-11e8-8af9-b44f4f5eaaf3.png)
